### PR TITLE
fixed: Compile with enabled experimental accelerometer

### PR DESCRIPTION
**Pull request by nechutny**
This change allow correct compilation of experimental accelerometer - was used bad constant.

### CODE REVIEW

**Review by BenjaminSoelberg — CHANGES_REQUESTED** [review]
Great to see your pull request!
Good idea to add mspdebug as an install target.
May I suggest that you also update README.md to add the new make target?

**Comment by nechutny** [comment]
Of course, I'll add it to readme. make usb-install was just another commit that i don't want merge now, but github added it to this pull request.

**Comment by BenjaminSoelberg** [comment]
Yeah I know. Git can be hard to handle. I have personally made a lot of bad commits and pushes. 
Do you want me to reject the pull request to give you a chance to create a new one ?

**Comment by BenjaminSoelberg** [comment]
You know what, i'll add your request to master. Thanks for the PR.

**Pull request merged**
